version: '3'

services:
  api:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 4200:4200
      - 9229:9229
    environment:
      ENV: 'development'
      POSTGRES_HOST: 'postgres'
      REDIS_URL: 'redis://redis:6379'
    depends_on:
      - postgres
      - redis

  postgres:
    image: mdillon/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: testescooter

  redis:
    image: redis
    ports:
      - 6379:6379
